name: DEV pullrequest - Build

on:
  pull_request:
    branches:
      - dev

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Packages (Backend)
        run: yarn install
        working-directory: Backend

      - name: Lint Backend
        run: yarn lint
        working-directory: Backend

      - name: Install Packages (Frontend)
        run: yarn install
        working-directory: Frontend

      - name: Build Frontend
        run: yarn build
        working-directory: Frontend

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: Frontend/build
